### ISSUE TITLE
Feature request: Support for typescript

### ISSUE THREAD

**Issue by Psycarlo** [YannisHofmann/react-native-country-flag#1]
`Could not find a declaration file for module 'react-native-country-flag'. 'c:/Users/xxx/xxx/xxx/node_modules/react-native-country-flag/src/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-native-country-flag` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-country-flag';``

**Comment by YannisHofmann** [comment]
Thank you, the package now supports TypeScript.
