### ISSUE TITLE
Reduce package size?

### ISSUE THREAD

**Issue by pierroo** [YannisHofmann/react-native-country-flag#4]
Hello,
As happy as I was to discover this new package, unfortunately it is not usable as of now in production because of the unzipped package size (11.2Mb! :/)

The react JS counter part (https://www.npmjs.com/package/react-country-flag) is nearly 1000x smaller in size

I see in your src that you use png, with absolutely insanely huge size.
Considering this is targeted at mobile, is there any plan on drastically reducing those png, or better yet, giving an alternative for "native emoji flags"?

**Comment by yucehasan** [comment]
+1

**Comment by YannisHofmann** [comment]
Hey, 
I have currently no time to do this, but maybe in a few weeks. But feel free to do a pull request.

**Comment by jandestiny** [comment]
+1
