### ISSUE TITLE
Add Additional "Non-Country Flags"

### ISSUE THREAD

**Issue by glynnallen1704** [YannisHofmann/react-native-country-flag#5]
Would be great to have "Euro" zone flags and other territories added here to. 
![download](https://user-images.githubusercontent.com/10270323/153227048-15f94f21-a36d-4095-b180-57c74c7c2595.png)

**Comment by YannisHofmann** [comment]
I have added the EU flag. If you miss any flags feel free to creat a issue or a pull request.
