### ISSUE TITLE
Not working on iOS Release

### ISSUE THREAD

**Issue by jorgmateos** [YannisHofmann/react-native-country-flag#6]
I'm trying to develop a list of phone prefixes with their respective flags and I'm getting an error in iOS, but only in Release.

I'm using React Native 0.60.1.

**Comment by beliemun** [comment]
I have same problem

**Comment by fullstackjedi** [comment]
Same issue

**Comment by Stophface** [comment]
Yep, same here. 
@beliemun @Emmanx @jorgmateos did you solve this? 
What is the exact error you are getting?

**Comment by fullstackjedi** [comment]
> Yep, same here. 
> 
> @beliemun @Emmanx @jorgmateos did you solve this? 
> 
> What is the exact error you are getting?

I solved it by rendering an emoji for iOS instead.

**Comment by jorgmateos** [comment]
> Yep, same here. @beliemun @Emmanx @jorgmateos did you solve this? What is the exact error you are getting?

I solved it by using another library 😅 This one seemed rather outdated and neglected 🤷🏻‍♂️

**Comment by lukaspechar** [comment]
> > Yep, same here. @beliemun @emmanx @jorgmateos did you solve this? What is the exact error you are getting?
> 
> I solved it by using another library 😅 This one seemed rather outdated and neglected 🤷🏻‍♂️

Would be good to know which one you used.

**Comment by jorgmateos** [comment]
> > > Yep, same here. @beliemun @emmanx @jorgmateos did you solve this? What is the exact error you are getting?
> > 
> > 
> > I solved it by using another library 😅 This one seemed rather outdated and neglected 🤷🏻‍♂️
> 
> Would be good to know which one you used.

I'm sorry but I'm no longer working on the project where I used this library. I don't have access to the code anymore either and I don't know which library I replaced it with 😢
